
version: 2.1

.env_common: &env_common
    SHELL: '/bin/bash'

.env_xdebug: &env_xdebug
    XDEBUG_MODE: 'coverage'

.env_composer: &env_composer
    COMPOSER_NO_INTERACTION: '1'
    COMPOSER_MEMORY_LIMIT: '-1'
    COMPOSER_DISABLE_XDEBUG_WARN: '1'
    COMPOSER_CACHE_DIR: '/home/circleci/.cache/composer'

orbs:
    codecov: 'codecov/codecov@1.2.0'

executors:
    php800:
        environment:
            <<: *env_common
            <<: *env_xdebug
            <<: *env_composer

        docker:
            -
                name: 'main'
                image: 'circleci/php:8.0'

    php704:
        environment:
            <<: *env_common
            <<: *env_xdebug
            <<: *env_composer

        docker:
            -
                name: 'main'
                image: 'circleci/php:7.4'

commands:
    composer_install:
        description: 'Install Composer dependencies with cache restore and save'
        steps:
            -
                restore_cache:
                    name: 'Composer - cache restore'
                    keys:
                        - 'composer-{{ checksum "./composer.lock" }}-1'

            -
                run:
                    name: 'Composer - install'
                    command: >
                        composer install --no-progress

            -
                save_cache:
                    name: 'Composer - cache save'
                    key: 'composer-{{ checksum "./composer.lock" }}-1'
                    paths:
                        - '~/.cache/composer'


    lint:
        description: 'Run linters'
        steps:
            -
                run:
                    name: 'Run linters'
                    command: 'bin/robo lint'

    test:
        description: 'Run tests'
        steps:
            -
                run:
                    name: 'Codeception - unit'
                    command: 'bin/robo test unit'
            -
                codecov/upload:
                    flags: 'unit'
                    file: './tests/_output/machine/coverage/unit/coverage.xml'
            -
                run:
                    name: 'Codeception - acceptance'
                    command: 'bin/robo test acceptance'
            -
                codecov/upload:
                    flags: 'acceptance'
                    file: './tests/_output/machine/coverage/acceptance/coverage.xml'
            -
                store_test_results:
                    name: 'Store unit test results'
                    path: './tests/_output/machine/junit'

jobs:
    build:
        executor: 'php704'
        working_directory: '~/repo'
        steps:
            - 'checkout'
            - 'composer_install'
    lint:
        executor: 'php704'
        working_directory: '~/repo'
        steps:
            - 'checkout'
            - 'composer_install'
            - 'lint'
    test_php800:
        executor: 'php800'
        working_directory: '~/repo'
        steps:
            - 'checkout'
            - 'composer_install'
            - 'test'
    test_php704:
        executor: 'php704'
        working_directory: '~/repo'
        steps:
            - 'checkout'
            - 'composer_install'
            - 'test'

workflows:
    lint_and_test:
        jobs:
            -
                build: {}
            -
                lint:
                    requires:
                        - 'build'
            -
                test_php800:
                    requires:
                        - 'build'
            -
                test_php704:
                    requires:
                        - 'build'
